name: Deploy Resume Site
on:
  push:
    branches: [ main ]
jobs:
  deploy-site:
    runs-on: self-hosted
    steps:
      - name: Update repository
        run: |
          cd ~/resume
          git fetch --all
          git reset --hard origin/main
      - name: Force remove existing container
        run: |
          cd ~/resume
          docker compose down
      - name: Build docker image
        run: |
          cd ~/resume
          docker compose build --no-cache
      - name: Run container
        run: |
          cd ~/resume
          docker compose up -d
      - name: Cleanup old images
        run: docker image prune -af 